# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prosibum' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prosibum

  # target 'prosibum-tvOSTests' do
  #
  # end

  target 'prosibumTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'RCTImage'
    ]

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-blur', :path => '../node_modules/react-native-blur'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'Interactable', :path => '../node_modules/react-native-interactable'


    pod 'react-native-config', :path => '../node_modules/react-native-config'


    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  end

end

# target 'prosibum-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prosibum-tvOS

  # target 'prosibum-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
