# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prosibum' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prosibum

  target 'prosibum-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'React', :path => '../node_modules/react-native'

    pod 'React', :path => '../node_modules/react-native'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  end

  target 'prosibumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'prosibum-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prosibum-tvOS

  # target 'prosibum-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
